# Generated by Django 5.0.1 on 2024-01-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
